swagger: '2.0'
info:
  version: 0.0.1
  title: 'ExAC21'
  description: 'Access the Exome Aggregation Consortium data (v0.3.1) on demand for bitcoin'
  x-21-quick-buy: '21 buy url http://10.244.188.146:5000/gene/PCSK9'
  x-21-category: utilities
  x-21-app-image:
  x-21-total-price:
    min: 1000
    max: 1000
  contact:
    name: Joe Pickrell
    email: joepickrell@gmail.com
host: 10.244.188.146:5000
schemes:
  - http
basePath: /
x-21-manifest-path: /manifest
paths:
  /gene/{id}:
     get:
        description: Returns all variants in a gene
        parameters:
          - name: id
            description: Name of gene (RefSeq format)
            in: path
            required: true
            type: string
        responses:
          200:
           description: list of variants
           schema:
             type: object
  /ensembl-gene/{id}:
     get:
        description: Returns all variants in a gene
        parameters:
          - name: id
            description: Name of gene (Ensembl ID)
            in: path
            required: true
            type: string
        responses:
          200:
           description: list of variants
           schema:
             type: object
  /lof/{id}:
     get:
        description: Returns all annotation loss-of-function variants in a gene
        parameters:
          - name: id
            description: Name of gene (RefSeq ID)
            in: path
            required: true
            type: string
        responses:
          200:
           description: list of variants
           schema:
             type: object
